name: Deploy ArquiusBot

on:
  push:
    branches:
      - master

# Detect whether the push touched core‑restart files or dependency files
jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      core_changed: ${{ steps.filter.outputs.core }}
      deps_changed: ${{ steps.filter.outputs.deps }}
    steps:
      - uses: actions/checkout@v4
      - id: filter
        uses: dorny/paths-filter@v2
        with:
          base: ${{ github.event.before }}
          filters: |
            core:
              - 'bot.py'
              - 'classes/discordbot.py'
            deps:
              - 'pyproject.toml'
              - 'uv.lock'

  deploy:
    needs: detect-changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        env:
          CORE_CHANGED: ${{ needs.detect-changes.outputs.core_changed }}
          DEPS_CHANGED: ${{ needs.detect-changes.outputs.deps_changed }}
        with:
          host: ${{ secrets.SERVER_IP }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: CORE_CHANGED,DEPS_CHANGED
          script: |
            set -euo pipefail
            CORE_CHANGED="${CORE_CHANGED:-false}"  # ← default if somehow unset
            DEPS_CHANGED="${DEPS_CHANGED:-false}"

            cd /home/makin/arquiusbot-2
            git pull origin master

            cat > config/bot.json <<'EOF'
            ${{ secrets.BOT_JSON }}
            EOF
            cat > config/cogs.json <<'EOF'
            ${{ secrets.COGS_JSON }}
            EOF

            if [ "$DEPS_CHANGED" = "true" ]; then
              /home/makin/.local/bin/uv sync --all-extras
            fi

            # Restart only if core logic or dependencies changed
            if [ "$CORE_CHANGED" = "true" ] || [ "$DEPS_CHANGED" = "true" ]; then
              sudo systemctl restart arquiusbot.service
            fi
