name: Deploy ArquiusBot

on:
  push:
    branches:
      - master

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      core_changed: ${{ steps.filter.outputs.core }}
      deps_changed: ${{ steps.filter.outputs.deps }}
    steps:
      - uses: actions/checkout@v4
      - id: filter
        uses: dorny/paths-filter@v2
        with:
          base: ${{ github.event.before }}
          filters: |
            core:
              - 'bot.py'
              - 'classes/discordbot.py'
            deps:
              - 'pyproject.toml'
              - 'uv.lock'

  deploy:
    needs: detect-changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        env:
          CORE_CHANGED: ${{ needs.detect-changes.outputs.core_changed }}
          DEPS_CHANGED: ${{ needs.detect-changes.outputs.deps_changed }}
          EXPORT_DIR:   ${{ secrets.EXPORT_DIR }}
        with:
          host:     ${{ secrets.SERVER_IP }}
          port:     ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USER }}
          key:      ${{ secrets.SSH_PRIVATE_KEY }}
          envs:     CORE_CHANGED,DEPS_CHANGED,EXPORT_DIR
          script: |
            set -euo pipefail
            CORE_CHANGED="${CORE_CHANGED:-false}"
            DEPS_CHANGED="${DEPS_CHANGED:-false}"

            cd "$EXPORT_DIR"
            git pull origin master

            # overwrite config from secrets
            cat > config/bot.json <<'EOF'
            ${{ secrets.BOT_JSON }}
            EOF
            cat > config/cogs.json <<'EOF'
            ${{ secrets.COGS_JSON }}
            EOF

            if [ "$DEPS_CHANGED" = "true" ]; then
              /home/makin/.local/bin/uv sync --all-extras
            fi

            if [ "$CORE_CHANGED" = "true" ] || [ "$DEPS_CHANGED" = "true" ]; then
              sudo systemctl restart arquiusbot.service
            fi
